### PR TITLE
Added 32x32 icons

### PR DESCRIPTION
**Pull request by MarkoMackic**

### CODE REVIEW

**Comment by MarkoMackic** [comment]
Referencing issue #221

**Comment by davsclaus** [comment]
Thanks. Its the PNG files that is what is actually being used by the plugin. The svg are _just_ the original source of the icon. I wonder if you could try to convert the svg to 32x32 png files?

I have found online converters that can do this on the internet in lack of a good app.

**Comment by MarkoMackic** [comment]
No problems, I'll commit it today

**Comment by davsclaus** [comment]
Thanks a lot

**Pull request merged**
