### PR TITLE
#264 Refined Camel route search scope

### PR DESCRIPTION
**Pull request by adrianbumbas**

### CODE REVIEW

**Comment by adrianbumbas** [comment]
For some reason this test fails from Maven but works when being run from IntelliJ. Does somebody have any idea why?

**Comment by davsclaus** [comment]
I am not sure why it fails

**Comment by fharms** [comment]
@adrianbumbas there is a few things you need to aware of when building from maven. 

1. It could be a dependency problem because of missing jar file.
2.The configuration in the failsafe maven plugin is customized for running the plugin test from maven. It's possible you need to configure additional properties.

My advice is to look through the log is printed out when running the build, and you might find the smoking gun. That at least what I have do in the past

**Comment by adrianbumbas** [comment]
I think that the problem is at the `maven-failsafe-plugin` configuration, it seems that the JVM options defined in the ` <argLine>` section are not passed to the test.

What is strange is that the `CamelProjectComponentTestIT` needs also the correct installation path but this one works. If I change `CamelRouteSearchScopeTest` to extend `ModuleTestCase` like `CamelProjectComponentTestIT` it doesn't work!

**Pull request merged**
